kind: pipeline
name: default

steps:
- name: install
  image: composer
  commands:
  - composer install

- name: test
  image: php:7
  commands:
  - vendor/bin/phpcs --standard=PSR2 src
  - vendor/bin/phpunit

